-- CreateTable
CREATE TABLE `User` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `email` VARCHAR(191) NOT NULL,
    `password` VARCHAR(191) NOT NULL,
    `nome` VARCHAR(191) NOT NULL,
    `role` VARCHAR(191) NOT NULL DEFAULT 'USER',
    `ativo` BOOLEAN NOT NULL DEFAULT true,
    `criadoEm` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `atualizadoEm` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`)
);

-- CreateIndex
CREATE UNIQUE INDEX `User_email_key` ON `User`(`email`);
